### ISSUE TITLE
Wiki bị lỗi hay sao ấy ,khong biết dùng wiki ở 0.5.7

### ISSUE THREAD

**Issue by BerVer266** [c3cbot/c3c-0x#17]
![20201203_182638](https://user-images.githubusercontent.com/73270862/101013396-ce73e380-3596-11eb-8915-2d4a031198c7.jpg)

**Comment by Udyz** [comment]
thôi bỏ đi bác

**Comment by Kaysil** [comment]
có commit fix từ 4 hôm trước rồi nhé

**Comment by Kaysil** [comment]
close đi
